#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

TEXT=$(cat "$1" | sed '/^#.*/d')
if [ -z $TEXT ]
  then
    echo 'commit msg is empty, please use git cz'
    exit 2
    fi
yarn commitlint --edit $1
commit=$(cat $1)
echo "OCT $commit" > "$1"
