#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
reg="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(.*)?: "
FILE=$1
MESSAGE=$(cat "$FILE")
echo "message $MESSAGE"
if [[ $MESSAGE =~ $reg ]];
  then
    echo "OCT $MESSAGE" > "$FILE"
  else
    exec < /dev/tty;
    git cz --hook || true;
fi
